name: Test with Nils

on:
  pull_request:
    branches: [ "main" ]

jobs:
#  build:
#    runs-on: self-hosted
#    steps:
#      - uses: actions/checkout@v4
#      - name: Build the image
#        run: docker build . --file Dockerfile --tag ninian:$(date +%Y-%m-%d_%H%M)
  deploy:
#    needs: build
    runs-on: self-hosted
    steps:
      - name: Just pull it idk
        run: cd /opt/veyle/nils
