name: Nils
on:
  pull_request:
    branches:
      - "main"
jobs:
  build:
    name: Build (dev)
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build the image.
        run: docker build . --file Dockerfile --tag registry.froginata.com/ninian:dev
      - name: Push and overwrite the last dev image.
        run: docker push registry.froginata.com/ninian:dev
