name: Ninian
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
jobs:
  stop:
    name: Stop Old Containers
    runs-on: self-hosted
    outputs:
      compose_dir: ${{ steps.stop-prod.outputs.compose_dir || steps.stop-dev.outputs.compose_dir }}
    steps:
      - id: stop-prod
        name: Let Ninian rest.
        if: github.ref == github.event.repository.default_branch
        run: |
          docker compose down
          docker rmi registry.froginata.com/ninian:latest
          echo "compose_dir=/opt/veyle/ninian" >> "$GITHUB_OUTPUT"
        working-directory: /opt/veyle/ninian
      - id: stop-dev
        name: Untag the old dev image.
        if: github.ref != github.event.repository.default_branch
        run: |
          docker compose down
          docker rmi registry.froginata.com/ninian:dev
          echo "compose_dir=/opt/veyle/nils" >> "$GITHUB_OUTPUT"
        working-directory: /opt/veyle/nils
  build:
    name: Build New Release
    runs-on: self-hosted
    steps:
      - name: Check out the new code.
        uses: actions/checkout@v4
      - name: Gather metadata.
        uses: docker/metadata-action@v6
        id: meta
        with:
          images: registry.froginata.com/ninian
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{date 'YYYY-MM-DD_HHmm'}},enable={{is_default_branch}}
            type=raw,value=dev,disable={{is_default_branch}}
          labels: |
            org.opencontainers.image.created={{commit_date 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'}}
      - name: Build & push the image!
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    name: Start New Containers
    runs-on: self-hosted
    needs: [stop, build]
    steps:
      - name: Load environmental variables.
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"
        working-directory: ${{ needs.stop.outputs.compose_dir }}
      - name: Send it!!
        run: docker compose up -d
        working-directory: ${{ needs.stop.outputs.compose_dir }}
      - name: Push the image to the registry for safekeeping.
        run: docker push registry.froginata.com/ninian:${IMAGE_TAG}
