name: Ninian
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
jobs:
  build:
    name: Build New Release
    runs-on: self-hosted
    steps:
      - name: Check out the new code.
        uses: actions/checkout@v4
      - name: Gather metadata.
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: registry.froginata.com/ninian
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{date 'YYYY-MM-DD_HHmm'}},enable={{is_default_branch}}
            type=raw,value=dev,enable={{!is_default_branch}}
          labels: |
            org.opencontainers.image.created={{commit_date 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'}}
      - name: Build & push the image!
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
